name: .NET Core

on: 
  release:
    types:
      - published

jobs:
  AspNetCoreHoneypot:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Build with dotnet
      run: dotnet build --configuration Release "./src"
    - name: Run unit tests
      run: dotnet test "./src"
    - name: Create the package
      run: dotnet pack --configuration Release "./src"
    - name: Publish "AspNetCore.Honeypot" to nuget
      run: dotnet nuget push "./src/AspNetCore.Honeypot/bin/Release/*.nupkg" -s "https://api.nuget.org/v3/index.json" -k ${{secrets.NUGET_API_KEY}}
